language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- pre-commit install
- pre-commit run --all-files
- pytest --cov=./
- codecov
env:
  global:
  - secure: BFGVxp8kU3f/sdxtM33Lv/ygmApczGlnDkckRyslbIebKc95GmkM080OTeq8QQVp+xr2OM3oMjy+rgRxUJIXcuhUDLnOgVTIv5Puszz3TM5koxr5U6927vLpnTJEyaJi7cgzJ4EohIKXJqKEVxHLWiJYl/2SaCL+rnl1MGjFtpkzaw+Fh9/79gB9ywmZiv+RhxPIaQESz3ZvRmJjS/4jAQFJxemc81Aol+EsF9FUzTAWWsd1bepzPm3e2VLq8Xc0qN2JxKiBDYtVRFLcQG7RHjmRQAFGFxEZgYaYi8rtE1Lnr1w30Ni3bVSIt0v8YbrGfYqnwfQKdK5dZZHK12Vl4zIe5fYRjhCTWuBRXqQFRyHwkMkmnNQ4Bm5h9j5MQJP9XliKinzHXkw7X+e+NHn4qfPlSNxcf0yDt60XZnnB9GhUARpnNF1sAwfFya5lXl2C+qVyi8N01jAnCLWCsj2UxVxrKJ6WL5gYePOe9ud2SChhPmR4ZMpOLM21Mc6CgXzBB1c6iRgr7RtYkMcmSa8AgbNXF7xRUIdfGdTMXM0N9JEXB81VHIeBnQvhG4PBlnyX9utb9EMz4wtyiskWzSk6nfPouubw0i90gaOCqGyxMck6NPRlfh/0FHevvGi2Y2uKmSHIlZrIoXUgxq4otw4s/kb9K5bz4m1DDf6GzIwKzBA=
  - secure: Q4Puk6fIkhRRU1z4NVQM8pJevNYH3YbGTAxB0nbmAXGgFLpDi9ztKepE8CbV8ntUpnn2GJQ90+5vStKls1FvsL/C28HUbPAaIynHUtsRf4cqRtVy6DMGGrSI9pByRnBmMuklo9Xz6N/bAKW7A89SsoYE169kgsgwqoRmlNT8biGB/iYmG42lSQ2CHTE47cbJMTdlsllO26zeV2198tsgCbDXmTtM/g/DJI9ncoZISy0/74t132jPNGV6uKn5dQazFHbDn2Ax+tfRVE8mGx2MG6+eJyR5pt+uwUDEFcRNd4izvPTyg4UCXoe3AFdFAtXvFr7wHfl3jyuq4vmG9KZIRRkXl+N9NhhtKMsgcp1OQuAS6AcDM4JFVHXVzO41Qj1ednhAALXwKuIvxbHpgB0d2YfhyHApLKSkI0fmFErL2tm4jEB0AjJ2CA7VxLR/5uveWS+FlRJ7VrRxTBi4RD6w+cUHTaLegGm5ZHFliHJyZt2xnOTH//gOb0/7D7od6bUE2sJwF84/GvzmVLGuJHD2fWsL+rOQMfY3+36qJ1UtwIiMrjNpAZwQ80rGCqcXyGnEKl2GHx3K2bAXqkXzV3Z0cu+Xi7KmH9GnAxsUmMMQcLkQwm2kdNGI53ppLeQMTvnk1AkX7YIC62h0jli2n5EiQG7vpxhurZUxJAhIWDfic+g=
